### PR TITLE
Update to vanilla 3.7.1 & update side navigation

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

Updates to vanilla 3.7.1 & updates side navigation to be compatible with 3.7.1

## QA

- Go to https://microk8s-io-554.demos.haus/docs# and check the side navigation has expandable child elements and works as expected.

## Issue / Card

Fixes https://github.com/canonical/microk8s.io/issues/553

### CODE REVIEW

**Comment by petesfrench** [comment]
Hey @evilnick, could you take a look at the demo for this and tell me if it looks right please? I am not sure a what level the sub-sections are supposed to expand/collapse. https://microk8s-io-554.demos.haus/#docs

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
Spotted a couple of things:
- as mentioned in standup, the highlighted style shouldn't apply to the entire block on page like: /docs/install-alternatives - on inspection it seems to be because the macro is setting the `aria-current="page"` attribute for all of those child items, perhaps because those child items are linking to sections on the same page, rather than linking to other pages?
- that highlighted state also prevents the cursor from changing to indicate that the child items are links/interactive.
- when visiting /docs/install-alternatives, the `aria-expanded` attribute is incorrectly set to `false` on the expanded item.

**Comment by evilnick** [comment]
Thanks for this work. It looks good to me whenever the other issues are resolved :+1:

**Review by sowasred2012 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
