### PR TITLE
MicroK8s refresh

### PR DESCRIPTION
**Pull request by mtruj013**
To be merged when all of the dev work in [this epic](https://warthogs.atlassian.net/browse/WD-3750) is complete.

### CODE REVIEW

**Comment by anthonydillon** [comment]
Forgive me if this is not the right place to file issues with the new build but looks like most of the PRs are merged.

1. The homepage hero content on small screen looks messy:


2. The logo on the install instructions looks too tight compared to the other platforms:


3. There is no URL change to the instructions. I would opt for landing on a specific page dedicated to installing in the platform to improve the UX.

4. There are sometimes different spacing under headings of the same type. Which makes the typography look messy:


5. Sometimes we use > after a link and others we don't:


6. There are some strange line breaks on small screens:


7. There are so many (mostly orange) tabs and pop ups that are very distracting (which is bad for a11y) and it's very likely to increase the bounce rate by frustrating the user.


8. Divided lists with bullets is strange and has never been part of Vanilla:


9. When in the docs section the docs navigation item is not selected.

**Comment by Sophie-32** [comment]
For Ant's comment 5. Links with a header such as webinars or blog post dont have an arrow. links without a header and 'stand alone' have the arrow.

Looking through the other feedback as well! Thanks Ant!

**Comment by lyubomir-popov** [comment]
@mtruj013 @anthonydillon design thoughts on the list of issues posted:

1. @mtruj013 please make the button, link and github icons on separate lines on small screens
2. tux logo already fixed by Camille, she has provided a link elsewhere
4. The bigger spacing is correct, please apply it to the ones thatdon't have it.
5. The use of chevrons is a way to highlight a link. I would leave it to @juanruitina to determine which links need to be highlighted like that.
6. @mtruj013 please apply the u-hide--small class on the br element causing the break
7. I agree, this looks horrible. Can we disable these on mobile or at least collapse them into 1 small icon?
8. this is actually the official list - here are all the variants: https://vanillaframework.io/docs/examples/patterns/lists/lists-dividers-all-wrapping

**Comment by juanruitina** [comment]
> Links with a header such as webinars or blog post dont have an arrow. links without a header and 'stand alone' have the arrow.

I agree with Sophie's rationale.

**Comment by lyubomir-popov** [comment]
@juanruitina can you please add this to the vanilla documentation? cc @bartaz

**Comment by Sophie-32** [comment]
@juanruitina @lyubomir-popov - I have a few things to add/change for Vanilla so I can take this for action too.

**Comment by Sophie-32** [comment]
> @juanruitina can you please add this to the vanilla documentation? cc @bartaz

@juanruitina @lyubomir-popov - i have a few things to add/change for vanilla so I can take this^ for action

**Comment by juanruitina** [comment]
Thank you @Sophie-32!

@mtruj013 Please adjust the "Find more resources" link to match this:

Screenshot 2023-09-01 at 10 28 55

That is, as a separate link instead of as a list item under Whitepapers. This will make the distinction clearer on mobile as well. I agreed with Lyubo on this. Thank you!!

**Review by bartaz — APPROVED** [review]
LGTM. 
QA'ed some pages, Vanilla 4 use is good (thanks!). A pity that still quite some custom CSS is needed, but I guess it's still unavoidable in some cases.

**Comment by mtruj013** [comment]
Thanks @bartaz !

**Pull request merged**
