### PR TITLE
Apply landing page redesign

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Applied redesign as per [doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?node-id=0%3A1&mode=dev)

**NOTE: Nav bar and footer to be updated in coming PR**

## QA

- View the site locally in your web browser at: https://microk8s-io-610.demos.haus/
- Check against doc and design

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3755

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
- Suru cropped on big screens:

image

- The h2 doesn't need an h4 class: 
 
image

- The space here should be p-section 64px:

image

- here too 
image

- 24px p-section--shallow:

image


- Video needs should be in the middle 6 columns:

image


- extra indent on the tabbed content:
- 
image


and I'll need to give you maco os and windows logos as the ones currently there are too big

**Comment by mtruj013** [comment]
@lyubomir-popov ready for another look!

**Comment by lyubomir-popov** [comment]
One last thing, in the last section, can we please get rid of the orphan by putting nbsps between the last 3 words? 
```
Insure your MicroK8s clusters 
with enterprise support
```

**Review by pedoch — APPROVED** [review]
LGTM! Thank you @mtruj013! Just a couple of minor comments.

**Pull request merged**
